name: seu_app
description: App que toca músicas MP3 e MP4
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0   # versão mais recente (MP3 e MP4 suportados)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/audio/   # PASTA OBRIGATÓRIA
